version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gocyclo
          - staticcheck
          - unparam
          - unused
        path: pkg/generated/*
      - linters:
          - lll
        path: cmd/*
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - dupl
          - lll
        path: pkg/utils/fakeclients/*
      - linters:
          - lll
        path: ^*_test.go
    paths:
      - tmp
      - pkg/generated/*
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - tmp
      - pkg/generated/*
      - third_party$
      - builtin$
      - examples$
