apiVersion: management.llmos.ai/v1
kind: Version
metadata:
  name: v0.2.0-rc1
spec:
  minUpgradableVersion: v0.1.0
  kubernetesVersion: v1.31.0+k3s1 # The newer k8s version to upgrade to
  releaseDate: "2024-09-30"
  tags: []
---
apiVersion: management.llmos.ai/v1
kind: Upgrade
metadata:
  name: llmos-upgrade-test
spec:
  version: v0.2.0-rc1 # The version to upgrade to
  registry: "docker.io/guangbo" # Override the default registry if needed
