apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: llmos-operator
  namespace: llmos-system
spec:
#  repo: https://ray-project.github.io/kuberay-helm
  repo: http://system-charts-repo.llmos-system.svc
  chart: llmos-operator
  version: v0.1.0
  enabled: true
  valuesContent: |-
    enabled: true
    image:
      repository: quay.io/kuberay/operator
      tag: v1.1.1
      pullPolicy: IfNotPresent
    batchScheduler:
      enabled: false
    serviceAccount:
      create: false
      name: llmos-cluster-admin
