# modelservice yaml file
apiVersion: ml.llmos.ai/v1
kind: ModelService
metadata:
  name: gemma-2-9b-it
spec:
  replicas: 1
  model: google/gemma-2-9b-it
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      runtimeClassName: nvidia
      containers:
        - name: server
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-token
                  key: token
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /root/.cache/huggingface
              name: hf-dir
          resources:
            limits:
              nvidia.com/gpu: "1"
      volumes:
        - emptyDir:
            medium: Memory
          name: dshm
  volumeClaimTemplates:
    - metadata:
        name: hf-dir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
  serviceType: ClusterIP
