#!/usr/bin/env bash
set -e -x

echo "--- chart/build ---"

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." &> /dev/null && pwd )"

cd "${TOP_DIR}"
. ./scripts/version

charts_dir=dist/charts
## create dist dir if not exist
if [ ! -d "${charts_dir}" ]; then
  mkdir -p "dist"
else
  rm -rf "${charts_dir}"
fi


cp -rf "${1}" "${charts_dir}"

function updateImageConfig() {
    # Update pullPolicy to IfNotPresent
    # Step 1: Convert YAML to JSON
    chart_path=$1
    cd "${chart_path}"
    yq eval -o=json values.yaml > values.json

    # Step 2: Use jq to update image config
    jq --arg tag "$TAG" '
      walk(
        if type == "object" then
          if has("pullPolicy") and .pullPolicy == "Always" then
            .pullPolicy = "IfNotPresent"
          else
            .
          end |
          if has("tag") and .tag == "main-head" then
            .tag = $tag
          else
            .
          end
        else
          .
        end
      )
    ' values.json > values-updated.json

    # Step 3: Convert JSON back to YAML
    yq eval -P values-updated.json -o yaml > values.yaml
    rm -f values.json values-updated.json
}

function patchChartVersion() {
    sed -i -e "s/0.1.0-dev/${CHART_VERSION}/g" "${llmos_crd_chart_path}/Chart.yaml"
    sed -i -e "s/0.1.0-app.dev/${APP_VERSION}/g" "${llmos_crd_chart_path}/Chart.yaml"
    sed -i -e "s/0.1.0-dev/${CHART_VERSION}/g" "${llmos_operator_chart_path}/Chart.yaml"
    sed -i -e "s/0.1.0-app.dev/${APP_VERSION}/g" "${llmos_operator_chart_path}/Chart.yaml"

    rm -f "${llmos_crd_chart_path}/Chart.yaml-e"
    rm -f "${llmos_operator_chart_path}/Chart.yaml-e"
}

# package llmos-operator chart
llmos_crd_chart_path=${charts_dir}/llmos-crd
llmos_operator_chart_path=${charts_dir}/llmos-operator


patchChartVersion
updateImageConfig "${llmos_operator_chart_path}"
cd "${TOP_DIR}"

echo "check helm exist"
# Check for helm
if [ -z "$(type -p helm)" ]; then
    echo "helm not found. Helm is required to run tests."
    exit 1
fi

helm lint "${llmos_crd_chart_path}"
helm lint "${llmos_operator_chart_path}"

helm package ${llmos_crd_chart_path} -d ${charts_dir} || true
helm package ${llmos_operator_chart_path} -d ${charts_dir} || true

helm repo index ${charts_dir} || true

rm -rf ${llmos_crd_chart_path} ${llmos_operator_chart_path}