#!/usr/bin/env bash
set -e

echo "--- Starting the build process for system charts ---"

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." &> /dev/null && pwd )"
SYSTEM_CHARTS_DIR=${SYSTEM_CHARTS_DIR:-deploy/charts/system-charts/charts}

cd "${TOP_DIR}"

# Source the version script
. ./scripts/version

CHART_DIST_DIR=${CHART_DIST_DIR:-dist/system-charts}
## check if dist dir exist
if [ ! -d "${CHART_DIST_DIR}" ]; then
  echo "Directory ${CHART_DIST_DIR} is not exist"
  exit 1
fi

./scripts/chart/check "${SYSTEM_CHARTS_DIR}"

echo "packaging system charts in ${CHART_DIST_DIR}"

cp -rf "${SYSTEM_CHARTS_DIR}"/* "${CHART_DIST_DIR}/"

# Lint the charts
echo "Linting Helm charts..."
if [ -e "${CHART_DIST_DIR}/index.yaml" ]; then
  rm -f "${CHART_DIST_DIR}/index.yaml"
fi

helm lint "${CHART_DIST_DIR}"/*

## Build the Helm repository index
echo "Building helm repo index.yaml"
helm repo index "${CHART_DIST_DIR}"
cat "${CHART_DIST_DIR}"/index.yaml || true


echo "Build system-charts repo completed successfully."
