---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: datacollections.agent.llmos.ai
spec:
  group: agent.llmos.ai
  names:
    kind: DataCollection
    listKind: DataCollectionList
    plural: datacollections
    shortNames:
    - dc
    - dcs
    singular: datacollection
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.registry
      name: Registry
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: DataCollection is a definition for the application data
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              registry:
                type: string
            required:
            - registry
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              files:
                items:
                  properties:
                    contentType:
                      type: string
                    etag:
                      type: string
                    lastModified:
                      format: date-time
                      type: string
                    name:
                      type: string
                    path:
                      type: string
                    size:
                      format: int64
                      type: integer
                    uid:
                      type: string
                  required:
                  - contentType
                  - etag
                  - lastModified
                  - name
                  - path
                  - size
                  - uid
                  type: object
                type: array
              rootPath:
                type: string
            required:
            - rootPath
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
