---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: tokens.management.llmos.ai
spec:
  group: management.llmos.ai
  names:
    kind: Token
    listKind: TokenList
    plural: tokens
    singular: token
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.annotations.field\.llmos\.io\/description
      name: Description
      type: string
    - jsonPath: .status.expiresAt
      name: Expires
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              authProvider:
                type: string
              expired:
                type: boolean
              token:
                type: string
              ttlSeconds:
                format: int64
                type: integer
              userId:
                type: string
            required:
            - authProvider
            - userId
            type: object
          status:
            properties:
              expiresAt:
                format: date-time
                type: string
              isExpired:
                type: boolean
            required:
            - isExpired
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
