---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: upgrades.management.llmos.ai
spec:
  group: management.llmos.ai
  names:
    kind: Upgrade
    listKind: UpgradeList
    plural: upgrades
    singular: upgrade
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.version
      name: Version
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Upgrade is the Schema for the upgrades API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: UpgradeSpec defines the desired state of Upgrade
            properties:
              drain:
                description: DrainSpec encapsulates `kubectl drain` parameters minus
                  node/pod selectors.
                properties:
                  deleteEmptydirData:
                    type: boolean
                  deleteLocalData:
                    type: boolean
                  disableEviction:
                    type: boolean
                  force:
                    type: boolean
                  gracePeriod:
                    format: int32
                    type: integer
                  ignoreDaemonSets:
                    type: boolean
                  podSelector:
                    description: |-
                      A label selector is a label query over a set of resources. The result of matchLabels and
                      matchExpressions are ANDed. An empty label selector matches all objects. A null
                      label selector matches no objects.
                    properties:
                      matchExpressions:
                        description: matchExpressions is a list of label selector
                          requirements. The requirements are ANDed.
                        items:
                          description: |-
                            A label selector requirement is a selector that contains values, a key, and an operator that
                            relates the key and values.
                          properties:
                            key:
                              description: key is the label key that the selector
                                applies to.
                              type: string
                            operator:
                              description: |-
                                operator represents a key's relationship to a set of values.
                                Valid operators are In, NotIn, Exists and DoesNotExist.
                              type: string
                            values:
                              description: |-
                                values is an array of string values. If the operator is In or NotIn,
                                the values array must be non-empty. If the operator is Exists or DoesNotExist,
                                the values array must be empty. This array is replaced during a strategic
                                merge patch.
                              items:
                                type: string
                              type: array
                              x-kubernetes-list-type: atomic
                          required:
                          - key
                          - operator
                          type: object
                        type: array
                        x-kubernetes-list-type: atomic
                      matchLabels:
                        additionalProperties:
                          type: string
                        description: |-
                          matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
                          map is equivalent to an element of matchExpressions, whose key field is "key", the
                          operator is "In", and the values array contains only "value". The requirements are ANDed.
                        type: object
                    type: object
                    x-kubernetes-map-type: atomic
                  skipWaitForDeleteTimeout:
                    type: integer
                  timeout:
                    description: |-
                      A Duration represents the elapsed time between two instants
                      as an int64 nanosecond count. The representation limits the
                      largest representable duration to approximately 290 years.
                    format: int64
                    type: integer
                type: object
              kubernetesVersion:
                type: string
              registry:
                type: string
              version:
                description: The LLMOS Operator version to upgrade to
                type: string
            required:
            - version
            type: object
          status:
            description: UpgradeStatus defines the observed state of Upgrade
            properties:
              PreviousKubernetesVersion:
                type: string
              appliedVersion:
                type: string
              completeTime:
                format: date-time
                type: string
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              managedAddonStatus:
                items:
                  properties:
                    complete:
                      type: boolean
                    disabled:
                      type: boolean
                    jobName:
                      type: string
                    lastUpdateTime:
                      format: date-time
                      type: string
                    name:
                      type: string
                  required:
                  - complete
                  - disabled
                  - name
                  type: object
                type: array
              nodeImageId:
                type: string
              nodeStatuses:
                additionalProperties:
                  properties:
                    message:
                      type: string
                    reason:
                      type: string
                    state:
                      type: string
                  type: object
                type: object
              planStatus:
                items:
                  properties:
                    complete:
                      type: boolean
                    lastUpdateTime:
                      format: date-time
                      type: string
                    latestHash:
                      type: string
                    latestVersion:
                      type: string
                    name:
                      type: string
                  required:
                  - complete
                  - name
                  type: object
                type: array
              previousVersion:
                type: string
              startTime:
                format: date-time
                type: string
              state:
                type: string
              upgradeJobs:
                items:
                  properties:
                    complete:
                      type: boolean
                    helmChartName:
                      type: string
                    lastUpdateTime:
                      format: date-time
                      type: string
                    name:
                      type: string
                  required:
                  - complete
                  - helmChartName
                  - name
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
