---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: versions.management.llmos.ai
spec:
  group: management.llmos.ai
  names:
    kind: Version
    listKind: VersionList
    plural: versions
    singular: version
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.minUpgradableVersion
      name: MIN UPGRADE VERSION
      type: string
    - jsonPath: .spec.releaseDate
      name: RELEASE DATE
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Version is the Schema for the upgrade version
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: VersionSpec defines the desired state of Version
            properties:
              kubernetesVersion:
                type: string
              minUpgradableVersion:
                type: string
              releaseDate:
                type: string
              tags:
                items:
                  type: string
                type: array
            required:
            - releaseDate
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
