---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: localmodels.ml.llmos.ai
spec:
  group: ml.llmos.ai
  names:
    kind: LocalModel
    listKind: LocalModelList
    plural: localmodels
    singular: localmodel
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.registry
      name: Registry
      type: string
    - jsonPath: .spec.modelName
      name: ModelName
      type: string
    - jsonPath: .status.defaultVersion
      name: DefaultVersion
      priority: 8
      type: integer
    - jsonPath: .status.latestVersion
      name: LatestVersion
      priority: 8
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: LocalModel is the model stored in the local storage
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              defaultVersion:
                description: DefaultVersion is the default version of the local model
                type: string
              modelName:
                description: ModelName is the name of the model in the registry like
                  deepseek-ai/deepseek-r1
                type: string
              registry:
                description: Registry can be the private registry or the public registry
                  like huggingface.co
                type: string
            required:
            - modelName
            - registry
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
