apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: kuberay-operator
  namespace: llmos-system
  labels:
    llmos.ai/system-addon: "true"
  annotations:
    field.llmos.ai/description: "KubeRay Operator manages the deployment and management of Ray applications and resources."
spec:
  repo: http://system-charts-repo.llmos-system.svc
  chart: kuberay-operator
  version: 1.1.1
  enabled: true
  valuesContent: |-
    image:
      repository: quay.io/kuberay/operator
      tag: v1.1.1
      pullPolicy: IfNotPresent
    batchScheduler:
      enabled: false
    serviceAccount:
      create: false
      name: llmos-cluster-admin
