apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: kuberay-operator
  namespace: llmos-system
  labels:
    llmos.ai/system-addon: "true"
  annotations:
    field.llmos.ai/description: "Facilitates the management of Ray clusters and other machine learning resources in your LLMOS cluster through the KubeRay Operator."
spec:
  repo: http://system-charts-repo.llmos-system.svc
  chart: kuberay-operator
  version: 1.2.1
  enabled: true
  defaultValuesContent: |-
    image:
      repository: quay.io/kuberay/operator
      pullPolicy: IfNotPresent
    batchScheduler:
      enabled: false
    serviceAccount:
      create: false
      name: llmos-cluster-admin
