apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: kuberay-operator
  namespace: llmos-system
  labels:
    llmos.ai/system-addon: "true"
  annotations:
    field.llmos.ai/description: "Facilitates the management of Ray clusters and other machine learning resources in your LLMOS cluster through the KubeRay Operator."
spec:
  repo: http://system-charts-repo.llmos-system.svc
  chart: kuberay-operator
  version: 1.3.0
  enabled: true
  defaultValuesContent: |-
    image:
      repository: ghcr.io/llmos-ai/mirrored-kuberay-operator
      pullPolicy: IfNotPresent
    batchScheduler:
      enabled: true
    serviceAccount:
      create: false
      name: llmos-cluster-admin
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 20m
        memory: 128Mi
