apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: llmos-redis
  namespace: llmos-system
  labels:
    llmos.ai/system-addon: "true"
  annotations:
    field.llmos.ai/description: "LLMOS-Redis provides a built-in Redis service for your cluster."
spec:
  repo: http://system-charts-repo.llmos-system.svc
  chart: redis
  version: 19.6.4
  enabled: true
  defaultValuesContent: |-
    image:
      repository: bitnami/redis
      pullPolicy: IfNotPresent
    ## @param architecture Redis&reg; architecture. Allowed values: `standalone` or `replication`
    ##
    architecture: replication
    master:
      count: 1
      persistence:
        enabled: true
        storageClass: ""
        accessModes:
          - ReadWriteOnce
        size: 5Gi
    replica:
      replicaCount: 0 # default to 0, scale up manually to 3 when the system storage is enabled
      persistence:
        enabled: true
        storageClass: ""
        accessModes:
          - ReadWriteOnce
        size: 5Gi
    auth:
      enabled: true
      sentinel: true
      password: ""
    volumePermissions:
      enabled: true
