apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: llmos-monitoring
  namespace: llmos-monitoring-system
  labels:
    llmos.ai/system-addon: "true"
    llmos.ai/system-addon-allow-edit: "true"
    llmos.ai/cluster-tools: "true"
  annotations:
    field.llmos.ai/description: "LLMOS monitoring provides an easy-to-use solution for cluster and GPU metrics 
    collection, complete with Grafana dashboards, Prometheus rules, and more for seamless end-to-end monitoring 
    using the Prometheus Operator."
spec:
  repo: http://system-charts-repo.llmos-system.svc
  chart: llmos-monitoring
  version: 0.1.5-up66.1.1
  enabled: false
  defaultValuesContent: |-
    nameOverride: "llmos-monitoring"
    namespaceOverride: "llmos-monitoring-system"
    crds:
      enabled: true
    global:
      k8s:
        provider: "k3s"
      llmos:
        systemDefaultRegistry: ""
        clusterId: "local"
        dashboardsNamespace: &dashboardsNamespace "llmos-dashboards"
        systemNamespace: "llmos-system"
      rbac:
        create: true
        createAggregateClusterRoles: false
        pspEnabled: false
        userRoles:
          create: true
          aggregateToDefaultRoles: true
    alertmanager:
      enabled: true
      alertmanagerSpec:
        image:
          registry: ghcr.io
          repository: llmos-ai/mirrored-prometheus-alertmanager
        useExistingSecret: false
        volumes: []
        alertmanagerConfigSelector:
          matchLabels:
            llmos.ai/alertmanagerconfig: "true"
      resources:
        limits:
          memory: 500Mi
          cpu: 1000m
        requests:
          memory: 100Mi
          cpu: 100m
    grafana:
      enabled: true
      image:
        registry: ghcr.io
        repository: llmos-ai/mirrored-grafana
      proxy:
        image:
          registry: ghcr.io
          repository: llmos-ai/mirrored-library-nginx
      sidecar:
        image:
          registry: ghcr.io
          repository: llmos-ai/mirrored-kiwigrid-k8s-sidecar
      resources:
        limits:
          memory: 200Mi
          cpu: 200m
        requests:
          memory: 100Mi
          cpu: 100m
    prometheusOperator:
      enabled: true
      image:
        registry: ghcr.io
        repository: llmos-ai/mirrored-prometheus-operator-prometheus-operator
      prometheusConfigReloader:
        image:
          registry: ghcr.io
          repository: llmos-ai/mirrored-prometheus-operator-prometheus-config-reloader
      admissionWebhooks:
        patch:
          enabled: true
          image:
            registry: ghcr.io
            repository: llmos-ai/mirrored-ingress-nginx-kube-webhook-certgen
      resources:
        limits:
          cpu: 500m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
    prometheus:
      enabled: true
      prometheusSpec:
        image:
          registry: ghcr.io
          repository: llmos-ai/mirrored-prometheus-prometheus
        enableAdminAPI: false
        ignoreNamespaceSelectors: false
        scrapeInterval: "30s"
        evaluationInterval: "30s"
        retention: 10d
        retentionSize: "50GiB"
        resources:
          limits:
            memory: 3000Mi
            cpu: 1000m
          requests:
            memory: 750Mi
            cpu: 750m
        storageSpec: {}
    kubeApiServer:
      enabled: true
    kubelet:
      enabled: true
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: true
    kubeEtcd:
      enabled: true
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeStateMetrics:
      enabled: true
    kube-state-metrics:
      image:
        registry: ghcr.io
        repository: llmos-ai/mirrored-kube-state-metrics
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 130Mi
    nodeExporter:
      enabled: true
      image:
        registry: ghcr.io
        repository: llmos-ai/mirrored-prometheus-node-exporter
    prometheus-node-exporter:
      image:
        registry: ghcr.io
        repository: llmos-ai/mirrored-prometheus-node-exporter
      resources:
        limits:
          cpu: 200m
          memory: 50Mi
        requests:
          cpu: 100m
          memory: 30Mi
    dcgmExporter:
      enabled: true
    modelServiceExporter:
      enabled: true
    rayExporter:
      enabled: true
