apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: llmos-agents
  namespace: llmos-agents
  labels:
    llmos.ai/system-addon: "true"
    llmos.ai/system-addon-allow-edit: "true"
    llmos.ai/cluster-tools: "true"
  annotations:
    field.llmos.ai/description: "llmos-agents is a simple toolkit for building and managing AI agents. It brings together vector databases and LLM tools to help you orchestrate, track, and validate your agents."
spec:
  repo: http://system-charts-repo.llmos-system.svc
  chart: llmos-agents
  version: 0.1.0-rc2
  enabled: false
  defaultValuesContent: |-
    langflow:
      backend:
        logLevel: INFO
        replicaCount: 1
        service:
          type: ClusterIP
          port: 7860
        backendOnly: true
        numWorkers: 1
        image:
          registry: ghcr.io
          repository: llmos-ai/mirrored-langflowai-langflow
          imagePullPolicy: IfNotPresent
        command:
          - python
          - -m
          - langflow
          - run
          - --host
          - 0.0.0.0
          - --backend-only
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 4
            memory: 8Gi
      frontend:
        enabled: true
        replicaCount: 1
        service:
          type: LoadBalancer
          port: 8080
        image:
          registry: ghcr.io
          repository: llmos-ai/mirrored-langflowai-langflow-frontend
          imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 0.2
            memory: 512Mi
          limits:
            cpu: 1
            memory: 2Gi

    postgresql:
      enabled: true
      name: postgres
      auth:
        enablePostgresUser: true
        postgresPassword: ""
        username: &postgresUser "llmos-agents"
        password: ""
        database: "llmos_agents"
      image:
        registry: ghcr.io
        repository: llmos-ai/mirrored-bitnami-postgresql
      architecture: replication
      primary:
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 2
            memory: 1024Mi
        persistence:
          enabled: true
          storageClass: ""
          accessModes:
            - ReadWriteOnce
          size: 8Gi
      readReplicas:
        persistence:
          enabled: true
          storageClass: ""
          accessModes:
            - ReadWriteOnce
          size: 8Gi

    weaviate:
      enabled: true
      image:
        registry: ghcr.io
        repo: llmos-ai/mirrored-semitechnologies-weaviate
      resources:
        requests:
          cpu: 200m
          memory: 300Mi
        limits:
          cpu: 2
          memory: 2Gi
      storage:
        size: 32Gi
        storageClassName: ""
