apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: llmos-operator-redis
  namespace: llmos-system
  labels:
    llmos.ai/system-addon: "true"
  annotations:
    field.llmos.ai/description: "LLMOS managed redis service for internal service storage."
spec:
  repo: http://system-charts-repo.llmos-system.svc
  chart: redis
  version: 19.6.4
  enabled: true
  valuesContent: |-
    image:
      repository: bitnami/redis
      tag: 7.2.5-debian-12-r4
      pullPolicy: IfNotPresent
    ## @param architecture Redis&reg; architecture. Allowed values: `standalone` or `replication`
    ##
    architecture: replication
    master:
      # default to 1, will auto-scale up to 1 by the operator when storage is ready
      count: 1
      persistence:
        enabled: true
        storageClass: ""
        accessModes:
          - ReadWriteOnce
        size: 5Gi
    replica:
      replicaCount: 0 # default to 0, will auto-scale up to 3 by the operator when storage is ready
      persistence:
        enabled: true
        storageClass: ""
        accessModes:
          - ReadWriteOnce
        size: 5Gi
    auth:
      enabled: true
      sentinel: true
      password: ""
    volumePermissions:
      enabled: true
