apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: rook-ceph
  namespace: llmos-system
  labels:
    llmos.ai/system-addon: "true"
  annotations:
    field.llmos.ai/description: "LLMOS managed rook-ceph operator for the cluster's build-in storage service."
spec:
  repo: http://system-charts-repo.llmos-system.svc
  chart: rook-ceph
  version: 1.14.9
  enabled: true
  valuesContent: |-
    image:
      repository: rook/ceph
      tag: v1.14.9
      pullPolicy: IfNotPresent
    crds:
      enabled: true
    csi:
      # -- Enable Ceph CSI RBD driver
      enableRbdDriver: true
      # -- Enable Ceph CSI CephFS driver
      enableCephfsDriver: true
      # -- Disable the CSI driver.
      disableCsiDriver: "false"
