apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: rook-ceph
  namespace: storage-system
  labels:
    llmos.ai/system-addon: "true"
  annotations:
    field.llmos.ai/description: "LLMOS managed rook-ceph operator for the cluster's build-in storage service."
spec:
  repo: http://system-charts-repo.llmos-system.svc
  chart: rook-ceph
  version: 1.15.3
  enabled: true
  defaultValuesContent: |-
    image:
      repository: ghcr.io/llmos-ai/mirrored-rook-ceph
      pullPolicy: IfNotPresent
    crds:
      enabled: true
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
    csi:
      # -- Enable Ceph CSI RBD driver
      enableRbdDriver: true
      # -- Enable Ceph CSI CephFS driver
      enableCephfsDriver: true
      # -- Disable the CSI driver.
      disableCsiDriver: "false"
      provisionerReplicas: 1 # default to 1
      registrar:
        repository: ghcr.io/llmos-ai/mirrored-sig-storage-csi-node-driver-registrar
      provisioner:
        repository: ghcr.io/llmos-ai/mirrored-sig-storage-csi-provisioner
      snapshotter:
        repository: ghcr.io/llmos-ai/mirrored-sig-storage-csi-snapshotter
      attacher:
        repository: ghcr.io/llmos-ai/mirrored-sig-storage-csi-attacher
      resizer:
        repository: ghcr.io/llmos-ai/mirrored-sig-storage-csi-resizer
