apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: system-upgrade-controller
  namespace: system-upgrade
  labels:
    llmos.ai/system-addon: "true"
  annotations:
    field.llmos.ai/description: "System-upgrade-controller helps to manage LLMOS nodes upgrade using Plans."
spec:
  repo: http://system-charts-repo.llmos-system.svc
  chart: system-upgrade-controller
  version: 0.1.0
  enabled: true
