apiVersion: management.llmos.ai/v1
kind: ManagedAddon
metadata:
  name: system-upgrade-controller
  namespace: system-upgrade
  labels:
    llmos.ai/system-addon: "true"
  annotations:
    field.llmos.ai/description: "System-upgrade-controller helps to manage LLMOS nodes upgrade using custom plans."
spec:
  repo: http://system-charts-repo.llmos-system.svc
  chart: system-upgrade-controller
  version: 0.1.1
  enabled: true
  defaultValuesContent: |-
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
