apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: llmos-system
type: Opaque
data:
  # echo -n <access key id> | base64
  # use echo -n to avoid the trailing newline
  accessKeyID: <access key id in base64>
  accessKeySecret: <access key secret in base64>