apiVersion: management.llmos.ai/v3
kind: GlobalRole
metadata:
  name: admin
spec:
  builtin: true
  displayName: Admin
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
status:
  conditions:
    - lastTransitionTime: "2024-08-29T03:27:51Z"
      message: cattle-globalrole-admin created
      reason: ClusterRoleExists
      status: "True"
      type: ClusterRoleExists
    - lastTransitionTime: "2024-08-29T03:27:51Z"
      message: admin-global-catalog created
      reason: CatalogRoleExists
      status: "True"
      type: CatalogRoleExists
  lastUpdateTime: 2024-08-29 03:27:51.773421734 +0000 UTC m=+30.512659151
  observedGeneration: 1
  summary: Completed
