apiVersion: ml.llmos.ai/v1
kind: Notebook
metadata:
  name: nb-code-server
  namespace: default
  labels:
    ml.llmos.ai/notebook-type: code-server
spec:
  template:
    spec:
      containers:
      - image: oneblockai/codeserver-python:latest
        name: nb-code-server
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        volumeMounts:
        - mountPath: /home/jovyan
          name: home-dir
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
  volumeClaimTemplates:
    - metadata:
        name: home-dir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
