apiVersion: ml.llmos.ai/v1
kind: Notebook
metadata:
  name: nb-jupyter
  namespace: default
  labels:
    ml.llmos.ai/notebook-type: jupyter
spec:
  serviceType: NodePort
  template:
    spec:
      containers:
      - image: oneblockai/jupyter-scipy:latest
        name: nb-jupyter
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        volumeMounts:
        - mountPath: /home/jovyan
          name: home-dir
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
  volumeClaimTemplates:
    - metadata:
        name: home-dir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
