name: test
on:
  pull_request:
    branches:
    - main
    - release-*

env:
  REGISTRY: ${{ vars.REGISTRY || 'ghcr.io/llmos-ai' }}
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY || 'docker.io/llmosai' }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
    - run: make test && make lint
    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: latest
        install-only: true
    - name: Build GoReleaser
      run: make build-operator
    - name: Setup Earthly
      uses: earthly/actions-setup@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version: "latest"
    - name: Run build system-charts repo image test
      run: make build-system-charts
    - name: Run build installer image test
      run: make build-installer
      env:
        UPLOAD_CHARTS: "false"
    - name: Run build node-upgrade image
      run: make build-upgrade
